version: '3.8'
services:
  web:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db_volume:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  db_volume:
    driver: local
    name: nestjs-mysql-db